apiVersion: v2
name: ks-gateway-autodns-server
description: A Helm chart for KubeSphere Gateway AutoDNS Server
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubesphere
  - gateway
  - autodns
  - dns
  - apisix
maintainers:
  - name: veater
