{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ks-gateway-autodns-server.fullname" . }}-mysql
  labels:
    {{- include "ks-gateway-autodns-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.auth.password | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ks-gateway-autodns-server.fullname" . }}-mysql
  labels:
    {{- include "ks-gateway-autodns-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "ks-gateway-autodns-server.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ks-gateway-autodns-server.fullname" . }}-mysql
  labels:
    {{- include "ks-gateway-autodns-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  serviceName: {{ include "ks-gateway-autodns-server.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      {{- include "ks-gateway-autodns-server.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        {{- include "ks-gateway-autodns-server.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "ks-gateway-autodns-server.fullname" . }}-mysql
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.auth.database | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.auth.username | quote }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "ks-gateway-autodns-server.fullname" . }}-mysql
              key: mysql-password
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        resources:
          {{- toYaml .Values.mysql.resources | nindent 10 }}
  {{- if .Values.mysql.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        {{- include "ks-gateway-autodns-server.labels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      accessModes:
        - ReadWriteOnce
      {{- if .Values.mysql.persistence.storageClass }}
      storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.mysql.persistence.size | quote }}
  {{- else }}
      volumes:
      - name: data
        emptyDir: {}
  {{- end }}
{{- end }}
